{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  labels:
{{ toYaml .Values.ingress.labels | indent 4 }}
  name: {{ template "helm-guestbook.fullname" . }}
spec:
  rules:
    - host: 
       - {{ .Values.ingress.hosts }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: ""
            backend:
              service:
                name: {{ template "helm-guestbook.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end -}}